const L=(id,code,name,color,stations,shape)=>({id,code,name,color,stations,shape});
export const countries=[
{id:'sg',flag:'🇸🇬',name:'Singapore',city:'Singapore',system:'MRT',lines:[
L('sg-ns','NS','North–South Line','#d42e12',['Jurong East','Bukit Batok','Bukit Gombak','Choa Chu Kang','Yew Tee','Kranji','Marsiling','Woodlands','Admiralty','Sembawang','Canberra','Yishun','Khatib','Yio Chu Kang','Ang Mo Kio','Bishan','Braddell','Toa Payoh','Novena','Newton','Orchard','Somerset','Dhoby Ghaut','City Hall','Raffles Place','Marina Bay','Marina South Pier'],[[20,75],[13,55],[18,22],[45,10],[55,42],[52,75],[65,88]]),
L('sg-ew','EW','East–West Line','#009645',['Pasir Ris','Tampines','Simei','Tanah Merah','Bedok','Kembangan','Eunos','Paya Lebar','Aljunied','Kallang','Lavender','Bugis','City Hall','Raffles Place','Tanjong Pagar','Outram Park','Tiong Bahru','Redhill','Queenstown','Commonwealth','Buona Vista','Dover','Clementi','Jurong East','Chinese Garden','Lakeside','Boon Lay','Pioneer','Joo Koon'],[[90,35],[72,48],[58,55],[47,65],[28,62],[9,68]]),
L('sg-ne','NE','North East Line','#9900aa',['HarbourFront','Outram Park','Chinatown','Clarke Quay','Dhoby Ghaut','Little India','Farrer Park','Boon Keng','Potong Pasir','Woodleigh','Serangoon','Kovan','Hougang','Buangkok','Sengkang','Punggol','Punggol Coast'],[[36,88],[48,70],[54,53],[65,36],[78,10]]),
L('sg-cc','CC','Circle Line','#fa9e0d',['Dhoby Ghaut','Bras Basah','Esplanade','Promenade','Nicoll Highway','Stadium','Mountbatten','Dakota','Paya Lebar','MacPherson','Tai Seng','Bartley','Serangoon','Lorong Chuan','Bishan','Marymount','Caldecott','Botanic Gardens','Farrer Road','Holland Village','Buona Vista','one-north','Kent Ridge','Haw Par Villa','Pasir Panjang','Labrador Park','Telok Blangah','HarbourFront'],[[54,70],[70,68],[82,52],[77,29],[58,17],[35,24],[20,43],[22,67],[35,83]]),
L('sg-dt','DT','Downtown Line','#005ec4',['Bukit Panjang','Cashew','Hillview','Beauty World','King Albert Park','Sixth Avenue','Tan Kah Kee','Botanic Gardens','Stevens','Newton','Little India','Rochor','Bugis','Promenade','Bayfront','Downtown','Telok Ayer','Chinatown','Fort Canning','Bencoolen','Jalan Besar','Bendemeer','Geylang Bahru','Mattar','MacPherson','Ubi','Kaki Bukit','Bedok North','Bedok Reservoir','Tampines West','Tampines','Tampines East','Upper Changi','Expo'],[[16,20],[30,40],[48,56],[62,77],[54,88],[72,72],[87,58],[91,78]])]},
{id:'my',flag:'🇲🇾',name:'Malaysia',city:'Kuala Lumpur',system:'Rapid KL',lines:[L('my-kl','MR','KL Monorail','#7bb241',['KL Sentral','Tun Sambanthan','Maharajalela','Hang Tuah','Imbi','Bukit Bintang','Raja Chulan','Bukit Nanas','Medan Tuanku','Chow Kit','Titiwangsa'],[[38,88],[43,65],[58,58],[63,35],[70,12]])]},
{id:'th',flag:'🇹🇭',name:'Thailand',city:'Bangkok',system:'BTS',lines:[L('th-suk','E','Sukhumvit Line','#65a844',['Khu Khot','Yaek Kor Por Aor','Royal Thai Air Force Museum','Bhumibol Adulyadej Hospital','Saphan Mai','Sai Yud','Phahon Yothin 59','Wat Phra Sri Mahathat','11th Infantry Regiment','Bang Bua','Royal Forest Department','Kasetsart University','Sena Nikhom','Ratchayothin','Phahon Yothin 24','Ha Yaek Lat Phrao','Mo Chit','Saphan Khwai','Ari','Sanam Pao','Victory Monument','Phaya Thai','Ratchathewi','Siam','Chit Lom','Phloen Chit','Nana','Asok','Phrom Phong','Thong Lo','Ekkamai','Phra Khanong','On Nut','Bang Chak','Punnawithi','Udom Suk','Bang Na','Bearing','Samrong','Pu Chao','Chang Erawan','Royal Thai Naval Academy','Pak Nam','Srinagarindra','Phraek Sa','Sai Luat','Kheha'],[[22,8],[34,32],[46,55],[62,61],[74,78],[80,92]])]},
{id:'hk',flag:'🇭🇰',name:'Hong Kong',city:'Hong Kong',system:'MTR',lines:[L('hk-island','ISL','Island Line','#0075c2',['Kennedy Town','HKU','Sai Ying Pun','Sheung Wan','Central','Admiralty','Wan Chai','Causeway Bay','Tin Hau','Fortress Hill','North Point','Quarry Bay','Tai Koo','Sai Wan Ho','Shau Kei Wan','Heng Fa Chuen','Chai Wan'],[[8,55],[28,50],[48,57],[68,48],[88,35]])]},
{id:'tw',flag:'🇹🇼',name:'Taiwan',city:'Taipei',system:'Taipei Metro',lines:[L('tw-red','R','Tamsui–Xinyi Line','#e3002c',['Tamsui','Hongshulin','Zhuwei','Guandu','Zhongyi','Fuxinggang','Beitou','Qiyan','Qilian','Shipai','Mingde','Zhishan','Shilin','Jiantan','Yuanshan','Minquan West Road','Shuanglian','Zhongshan','Taipei Main Station','National Taiwan University Hospital','Chiang Kai-Shek Memorial Hall','Dongmen','Daan Park','Daan','Xinyi Anhe','Taipei 101/World Trade Center','Xiangshan'],[[18,8],[24,30],[35,48],[52,60],[70,70],[88,77]])]},
{id:'kr',flag:'🇰🇷',name:'South Korea',city:'Seoul',system:'AREX',lines:[L('kr-arex','A','Airport Railroad','#0090d2',['Seoul Station','Gongdeok','Hongik University','Digital Media City','Magongnaru','Gimpo International Airport','Gyeyang','Geomam','Cheongna International City','Yeongjong','Unseo','Airport Cargo Terminal','Incheon International Airport Terminal 1','Incheon International Airport Terminal 2'],[[88,30],[70,35],[50,46],[32,58],[12,72]])]},
{id:'jp',flag:'🇯🇵',name:'Japan',city:'Tokyo & Osaka',system:'Metro / JR',lines:[
L('jp-ginza','G','Tokyo Ginza Line','#f39700',['Shibuya','Omote-sando','Gaiemmae','Aoyama-itchome','Akasaka-mitsuke','Tameike-sanno','Toranomon','Shimbashi','Ginza','Kyobashi','Nihombashi','Mitsukoshimae','Kanda','Suehirocho','Ueno-hirokoji','Ueno','Inaricho','Tawaramachi','Asakusa'],[[12,75],[38,58],[55,60],[70,42],[88,28]]),
L('jp-maru','M','Tokyo Marunouchi Line','#e60012',['Ogikubo','Minami-asagaya','Shin-koenji','Higashi-koenji','Shin-nakano','Nakano-sakaue','Nishi-shinjuku','Shinjuku','Shinjuku-sanchome','Shinjuku-gyoemmae','Yotsuya-sanchome','Yotsuya','Akasaka-mitsuke','Kokkai-gijidomae','Kasumigaseki','Ginza','Tokyo','Otemachi','Awajicho','Ochanomizu','Hongo-sanchome','Korakuen','Myogadani','Shin-otsuka','Ikebukuro'],[[8,48],[28,55],[42,42],[58,62],[72,45],[82,18]]),
L('jp-yama','JY','Yamanote Line','#84bd00',['Tokyo','Kanda','Akihabara','Okachimachi','Ueno','Uguisudani','Nippori','Nishi-Nippori','Tabata','Komagome','Sugamo','Otsuka','Ikebukuro','Mejiro','Takadanobaba','Shin-Okubo','Shinjuku','Yoyogi','Harajuku','Shibuya','Ebisu','Meguro','Gotanda','Osaki','Shinagawa','Takanawa Gateway','Tamachi','Hamamatsucho','Shimbashi','Yurakucho'],[[55,12],[76,18],[87,40],[82,70],[62,88],[35,85],[14,65],[12,35],[32,16],[55,12]]),
L('jp-mido','M','Osaka Midosuji Line','#e5171f',['Esaka','Higashi-mikuni','Shin-Osaka','Nishinakajima-Minamigata','Nakatsu','Umeda','Yodoyabashi','Hommachi','Shinsaibashi','Namba','Daikokucho','Dobutsuen-mae','Tennoji','Showacho','Nishitanabe','Nagai','Abiko','Kita-hanada','Shinkanaoka','Nakamozu'],[[50,7],[48,28],[51,50],[47,72],[53,94]])]},
{id:'gb',flag:'🇬🇧',name:'United Kingdom',city:'London',system:'Underground',lines:[
L('gb-vic','V','Victoria Line','#00a0e2',['Walthamstow Central','Blackhorse Road','Tottenham Hale','Seven Sisters','Finsbury Park','Highbury & Islington','King’s Cross St Pancras','Euston','Warren Street','Oxford Circus','Green Park','Victoria','Pimlico','Vauxhall','Stockwell','Brixton'],[[75,8],[65,30],[55,46],[48,64],[35,88]]),
L('gb-jub','J','Jubilee Line','#7c878e',['Stanmore','Canons Park','Queensbury','Kingsbury','Wembley Park','Neasden','Dollis Hill','Willesden Green','Kilburn','West Hampstead','Finchley Road','Swiss Cottage','St John’s Wood','Baker Street','Bond Street','Green Park','Westminster','Waterloo','Southwark','London Bridge','Bermondsey','Canada Water','Canary Wharf','North Greenwich','Canning Town','West Ham','Stratford'],[[10,12],[25,31],[40,48],[50,70],[65,62],[77,78],[90,60]])]}
];
export const allLines=countries.flatMap(c=>c.lines.map(l=>({...l,countryId:c.id,country:c.name,city:c.city})));
